repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: deno fmt
        language: system
        types_or: [javascript, jsx, ts, tsx, json, markdown]
      - id: lint
        name: lint
        entry: deno lint
        language: system
        types_or: [javascript, jsx, ts, tsx, json, markdown]
